"""V3 diagnostic for Chronicle Fury action semantics and observable state.

This module is deliberately a diagnostic layer over the frozen V2 policy.  It
does not publish a runner artifact.  It narrows labels to the 15 actions the
current Cat2/simulator bridge can issue, separates decisions from procs and
cast outcomes, and adds only information observable strictly before a label.
"""

from __future__ import annotations

import argparse
from bisect import bisect_right
from collections import Counter, defaultdict
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass, field
import json
from pathlib import Path
from typing import Any

from . import chronicle_external_historical_fury_policy_v2 as policy_v2
from .chronicle_combatant_sidecar import (
    RECORD_SCHEMA as COMBATANT_RECORD_SCHEMA,
    decode_combatant_info_stream,
    sidecar_records,
)


JSONMap = dict[str, Any]
SCHEMA = "chronicle_external_historical_fury_policy_v3_diagnostic/v1"
STATUS = "DIAGNOSTIC_NONVOTING_NOT_RUNNER_ADMITTED"

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_ADMISSION_MANIFEST = (
    PROJECT_ROOT
    / "offline_data"
    / "derived"
    / "chronicle_external_reconstruction_admission"
    / "v1"
    / "utk_postfix_dev_20260903_noon"
    / "manifest.json"
)


ROLE_CONTROLLABLE_START = "CONTROLLABLE_DECISION_START"
ROLE_CONTROLLABLE_INSTANT_GO = "CONTROLLABLE_DECISION_UNPAIRED_INSTANT_GO"
ROLE_PAIRED_RESULT = "PAIRED_GO_RESULT"
ROLE_EXOGENOUS = "EXOGENOUS_EVENT"
ROLE_CONTROLLED_OUTCOME = "CONTROLLED_OUTCOME_NOT_DECISION"
ROLE_OUT_OF_ONTOLOGY = "CONTROLLABLE_OUT_OF_ONTOLOGY"
ROLE_UNRESOLVED_GO = "UNRESOLVED_GO_NOT_DECISION_EVIDENCE"
ROLE_FAILED_ATTEMPT = "FAILED_CONTROLLABLE_ATTEMPT"


@dataclass(frozen=True)
class ActionSpec:
    action_key: str
    spell_ids: frozenset[int]
    name_aliases: frozenset[str]
    lane: str
    unpaired_go_is_decision: bool


def _aliases(*values: str) -> frozenset[str]:
    return frozenset(value.strip().casefold() for value in values)


# These are the exact commands exposed by the current Cat2/simulator bridge.
# Multiple IDs are retained only where local Turtle evidence records two live
# top-rank IDs.  Result-only spell IDs are listed separately below.
ACTION_ONTOLOGY: tuple[ActionSpec, ...] = (
    ActionSpec("warrior.battle_shout", frozenset({25289}), _aliases("Battle Shout", "战斗怒吼"), "gcd", True),
    ActionSpec("warrior.battle_stance", frozenset({2457}), _aliases("Battle Stance", "战斗姿态"), "off_gcd", True),
    ActionSpec("warrior.berserker_stance", frozenset({2458}), _aliases("Berserker Stance", "狂暴姿态"), "off_gcd", True),
    ActionSpec("warrior.bloodrage", frozenset({2687}), _aliases("Bloodrage", "血性狂暴"), "off_gcd", True),
    ActionSpec("warrior.bloodthirst", frozenset({23894}), _aliases("Bloodthirst", "嗜血"), "gcd", True),
    ActionSpec("warrior.death_wish", frozenset({12328}), _aliases("Death Wish", "死亡之愿"), "gcd", True),
    ActionSpec("warrior.defensive_stance", frozenset({71}), _aliases("Defensive Stance", "防御姿态"), "off_gcd", True),
    ActionSpec("warrior.execute", frozenset({20662}), _aliases("Execute", "斩杀"), "gcd", True),
    ActionSpec("warrior.hamstring", frozenset({7373}), _aliases("Hamstring", "断筋"), "gcd", True),
    ActionSpec("warrior.pummel", frozenset({6552}), _aliases("Pummel", "拳击"), "gcd", True),
    ActionSpec("warrior.slam", frozenset({45961}), _aliases("Slam", "猛击"), "gcd", False),
    ActionSpec("warrior.sunder_armor", frozenset({11597}), _aliases("Sunder Armor", "破甲攻击"), "gcd", True),
    ActionSpec("warrior.whirlwind", frozenset({1680}), _aliases("Whirlwind", "旋风斩"), "gcd", True),
    ActionSpec("warrior.heroic_strike", frozenset({11567, 25286}), _aliases("Heroic Strike", "英勇打击"), "queue", False),
    ActionSpec("warrior.cleave", frozenset({20569}), _aliases("Cleave", "顺劈斩"), "queue", False),
)

_SPEC_BY_ID = {
    spell_id: spec for spec in ACTION_ONTOLOGY for spell_id in spec.spell_ids
}
_SPEC_BY_NAME = {
    alias: spec for spec in ACTION_ONTOLOGY for alias in spec.name_aliases
}

# Known autonomous procs.  Unknown GO rows are not asserted to be procs: they
# remain unresolved because a GO alone does not establish a player decision.
EXOGENOUS_SPELL_IDS = frozenset({12721, 12966, 12967, 12968, 12969, 12970})
EXOGENOUS_NAMES = _aliases("Deep Wounds", "Flurry", "重伤", "乱舞")

# Triggered damage/results generated by a controllable cast are outcomes, not
# a second action choice.  Execute wrapper 20662 remains the decision ID.
CONTROLLED_RESULT_SPELL_IDS = frozenset(
    {20647, 45599, 45960, 45963, 45964, 53214}
)

COOLDOWN_PROXY_ACTIONS = (
    "warrior.bloodrage",
    "warrior.bloodthirst",
    "warrior.death_wish",
    "warrior.pummel",
    "warrior.whirlwind",
)

MISSING_DYNAMIC_STATE = (
    "current rage and incoming-rage timing",
    "exact global-cooldown remaining",
    "exact cooldown/reset/shared-cooldown state",
    "aura identity, stacks, and remaining duration",
    "main/off-hand swing deadlines and next-swing queue intent",
    "initial stance before the first observed stance action",
    "target health/execute phase, range, position, line of sight, and attackability",
    "dynamic attack power, weapon speed, and temporary proc state",
)


@dataclass(frozen=True)
class ActionClassification:
    role: str
    action_key: str | None
    lane: str | None
    spell_id: int | None


def _spell_parts(spell: Mapping[str, Any]) -> tuple[int | None, str | None]:
    raw_id = spell.get("id")
    spell_id = (
        raw_id
        if isinstance(raw_id, int) and not isinstance(raw_id, bool) and raw_id > 0
        else None
    )
    raw_name = spell.get("name")
    name = raw_name.strip().casefold() if isinstance(raw_name, str) and raw_name.strip() else None
    return spell_id, name


def _action_spec(spell: Mapping[str, Any]) -> ActionSpec | None:
    spell_id, name = _spell_parts(spell)
    if spell_id is not None:
        return _SPEC_BY_ID.get(spell_id)
    return _SPEC_BY_NAME.get(name) if name is not None else None


def classify_action_event(
    *, event_type: str, spell: Mapping[str, Any]
) -> ActionClassification:
    """Classify one Chronicle START/GO/FAIL without guessing from a GO name."""

    if event_type not in {"START", "GO", "FAIL"}:
        raise ValueError(f"unsupported action event type: {event_type}")
    spell_id, name = _spell_parts(spell)
    if spell_id in EXOGENOUS_SPELL_IDS or (
        spell_id is None and name in EXOGENOUS_NAMES
    ):
        return ActionClassification(ROLE_EXOGENOUS, None, None, spell_id)
    if spell_id in CONTROLLED_RESULT_SPELL_IDS:
        return ActionClassification(ROLE_CONTROLLED_OUTCOME, None, None, spell_id)

    spec = _action_spec(spell)
    if spec is None:
        role = ROLE_OUT_OF_ONTOLOGY if event_type in {"START", "FAIL"} else ROLE_UNRESOLVED_GO
        return ActionClassification(role, None, None, spell_id)
    if event_type == "FAIL":
        return ActionClassification(
            ROLE_FAILED_ATTEMPT, spec.action_key, spec.lane, spell_id
        )
    if event_type == "START":
        return ActionClassification(
            ROLE_CONTROLLABLE_START, spec.action_key, spec.lane, spell_id
        )
    if spec.unpaired_go_is_decision:
        return ActionClassification(
            ROLE_CONTROLLABLE_INSTANT_GO, spec.action_key, spec.lane, spell_id
        )
    return ActionClassification(
        ROLE_CONTROLLED_OUTCOME, spec.action_key, spec.lane, spell_id
    )


@dataclass(frozen=True)
class CharacterInventorySnapshot:
    instance_ref: str
    encounter_id: str
    player_guid: str
    event_index: int
    message_ordinal: int
    gear_slots: tuple[JSONMap, ...]
    talent_summary: tuple[int, ...] | None
    talent_trees: tuple[str, ...] | None

    def feature_profile(self) -> JSONMap:
        return {
            "gear_slots": [dict(slot) for slot in self.gear_slots],
            "talent_summary": (
                list(self.talent_summary) if self.talent_summary is not None else None
            ),
            "talent_trees": (
                list(self.talent_trees) if self.talent_trees is not None else None
            ),
        }


class CharacterInventoryIndex:
    """Small causal INFO index preserving slot/enchant/gem/talent fields."""

    def __init__(self, records: Iterable[Mapping[str, Any]]) -> None:
        grouped: dict[
            tuple[str, str, str], list[CharacterInventorySnapshot]
        ] = defaultdict(list)
        observed_encounters: set[tuple[str, str]] = set()
        observed_players: set[tuple[str, str, str]] = set()
        for record in records:
            if record.get("schema") != COMBATANT_RECORD_SCHEMA:
                raise ValueError(f"unsupported CombatantInfo row schema: {record.get('schema')!r}")
            instance_ref = str(record.get("instance_ref") or "")
            encounter_id = str(record.get("encounter_id") or "")
            player = record.get("player")
            if not instance_ref or not encounter_id or not isinstance(player, Mapping):
                raise ValueError("CombatantInfo row is missing instance/encounter/player")
            player_guid = str(player.get("guid") or "").strip().lower()
            if not player_guid:
                raise ValueError("CombatantInfo row is missing exact player GUID")
            key = (instance_ref, encounter_id, player_guid)
            observed_encounters.add((instance_ref, encounter_id))
            observed_players.add(key)
            anchor = record.get("anchor")
            if anchor is None:
                continue
            if not isinstance(anchor, Mapping):
                raise ValueError("CombatantInfo anchor must be an object")
            event_index = anchor.get("event_index")
            ordinal = record.get("message_ordinal")
            if (
                isinstance(event_index, bool)
                or not isinstance(event_index, int)
                or isinstance(ordinal, bool)
                or not isinstance(ordinal, int)
            ):
                raise ValueError("CombatantInfo event index/ordinal must be integers")
            grouped[key].append(
                CharacterInventorySnapshot(
                    instance_ref=instance_ref,
                    encounter_id=encounter_id,
                    player_guid=player_guid,
                    event_index=event_index,
                    message_ordinal=ordinal,
                    gear_slots=_gear_slots(record.get("gear")),
                    talent_summary=_talent_summary(record.get("talents")),
                    talent_trees=_talent_trees(record.get("talents")),
                )
            )
        self._observed_encounters = observed_encounters
        self._observed_players = observed_players
        self._rows: dict[
            tuple[str, str, str], tuple[tuple[tuple[int, int], ...], tuple[CharacterInventorySnapshot, ...]]
        ] = {}
        for key, values in grouped.items():
            ordered = tuple(sorted(values, key=lambda row: (row.event_index, row.message_ordinal)))
            self._rows[key] = (
                tuple((row.event_index, row.message_ordinal) for row in ordered),
                ordered,
            )

    def select(
        self,
        *,
        instance_ref: str,
        encounter_id: str,
        player_guid: str,
        event_index: int,
    ) -> tuple[CharacterInventorySnapshot | None, str]:
        key = (instance_ref, encounter_id, player_guid.strip().lower())
        if (instance_ref, encounter_id) not in self._observed_encounters:
            return None, "encounter_missing"
        if key not in self._observed_players:
            return None, "guid_mismatch"
        found = self._rows.get(key)
        if found is None:
            return None, "unanchored_info_only"
        anchors, rows = found
        position = bisect_right(anchors, (event_index, 2**63 - 1))
        if position == 0:
            return None, "late_info_only"
        return rows[position - 1], "matched"


def _gear_slots(raw: Any) -> tuple[JSONMap, ...]:
    if not isinstance(raw, list):
        return ()
    result: list[JSONMap] = []
    for slot in raw:
        if not isinstance(slot, Mapping):
            raise ValueError("CombatantInfo gear slot must be an object")
        slot_index = slot.get("slot_index")
        item_id = slot.get("item_id")
        if any(isinstance(value, bool) or not isinstance(value, int) for value in (slot_index, item_id)):
            raise ValueError("CombatantInfo slot_index/item_id must be integers")
        gems = slot.get("gem_enchant_ids", [])
        if not isinstance(gems, list) or any(isinstance(value, bool) or not isinstance(value, int) for value in gems):
            raise ValueError("CombatantInfo gem enchant IDs must be integers")
        result.append(
            {
                "slot_index": slot_index,
                "item_id": item_id,
                "enchant_id": slot.get("enchant_id"),
                "temporary_enchant_id": slot.get("temporary_enchant_id"),
                "gem_enchant_ids": list(gems),
            }
        )
    return tuple(sorted(result, key=lambda row: row["slot_index"]))


def _talent_summary(raw: Any) -> tuple[int, ...] | None:
    if not isinstance(raw, Mapping):
        return None
    values = raw.get("summary")
    if not isinstance(values, list) or any(isinstance(value, bool) or not isinstance(value, int) for value in values):
        return None
    return tuple(values)


def _talent_trees(raw: Any) -> tuple[str, ...] | None:
    if not isinstance(raw, Mapping):
        return None
    values = raw.get("trees")
    if not isinstance(values, list) or not all(isinstance(value, str) for value in values):
        return None
    return tuple(values)


def inventory_index_from_compressed_stream(
    compressed: bytes, *, instance_ref: str, slug: str
) -> CharacterInventoryIndex:
    """Decode one small official CombatantInfo object into a causal index."""

    frames = decode_combatant_info_stream(compressed)
    return CharacterInventoryIndex(
        sidecar_records(frames, instance_ref=instance_ref, slug=slug)
    )


@dataclass(frozen=True)
class PrefixAction:
    action_key: str
    lane: str
    timestamp_ms: int
    trace_index: int


@dataclass(frozen=True)
class AcceptedDecision:
    action_key: str
    event_role: str
    trace_index: int
    voting_usable: bool
    inventory_join_outcome: str
    contexts: Mapping[str, str]


@dataclass
class PlayerDiagnostic:
    aggregate: policy_v2._Aggregate = field(default_factory=policy_v2._Aggregate)
    decisions: list[AcceptedDecision] = field(default_factory=list)
    audit: Counter[str] = field(default_factory=Counter)
    feature_coverage: Counter[str] = field(default_factory=Counter)


def _action_identity(
    action_key: str, label: Mapping[str, Any]
) -> tuple[str, str]:
    target = label.get("target")
    target_guid = target.get("guid") if isinstance(target, Mapping) else None
    return action_key, target_guid if isinstance(target_guid, str) else ""


def _age_bucket(current_ms: int, previous_ms: int | None) -> str:
    if previous_ms is None:
        return "NEVER_OBSERVED"
    return policy_v2._elapsed_bucket(max(0, current_ms - previous_ms))


def _contexts_with_observable_state(
    *,
    state: Mapping[str, Any],
    trace: Sequence[Mapping[str, Any]],
    focal_guid: str,
    current_timestamp_ms: int,
    history: Sequence[PrefixAction],
    inventory: CharacterInventorySnapshot | None,
) -> dict[str, str]:
    base = {
        level: json.loads(value)
        for level, value in policy_v2._contexts_from_prefix(
            state=state, trace=trace, focal_guid=focal_guid
        ).items()
    }
    recent = list(history[-2:])
    last = recent[-1] if recent else None
    prior = recent[-2] if len(recent) == 2 else None
    last_gcd = next((row for row in reversed(history) if row.lane == "gcd"), None)
    last_queue = next((row for row in reversed(history) if row.lane == "queue"), None)
    observed_stance = next(
        (
            row.action_key.removeprefix("warrior.")
            for row in reversed(history)
            if row.action_key
            in {
                "warrior.battle_stance",
                "warrior.defensive_stance",
                "warrior.berserker_stance",
            }
        ),
        "UNKNOWN_BEFORE_OBSERVED_STANCE_ACTION",
    )
    tactical_patch = {
        # Replace V2's any-START/GO feature, which admitted proc GO rows.
        "last_prefix_action_spell": last.action_key if last else "NONE",
        "previous_controllable_action": prior.action_key if prior else "NONE",
        "last_controllable_action_age": _age_bucket(
            current_timestamp_ms, last.timestamp_ms if last else None
        ),
        "last_gcd_action_age": _age_bucket(
            current_timestamp_ms, last_gcd.timestamp_ms if last_gcd else None
        ),
        "last_queue_decision_age": _age_bucket(
            current_timestamp_ms, last_queue.timestamp_ms if last_queue else None
        ),
        "stance_after_observed_action": observed_stance,
        "static_character_inventory_observed": inventory is not None,
    }
    base["tactical"].update(tactical_patch)
    base["full"].update(tactical_patch)
    latest_by_action = {row.action_key: row.timestamp_ms for row in history}
    base["full"]["cooldown_action_age_proxies"] = {
        action_key: _age_bucket(current_timestamp_ms, latest_by_action.get(action_key))
        for action_key in COOLDOWN_PROXY_ACTIONS
    }
    base["full"]["static_character_profile"] = (
        inventory.feature_profile() if inventory is not None else "MISSING"
    )
    return {
        level: policy_v2._canonical_bytes(base[level]).decode("utf-8")
        for level in policy_v2.CONTEXT_LEVELS
    }


def _validate_transition(
    transition: Mapping[str, Any],
    *,
    trace: Sequence[Mapping[str, Any]],
    focal_guid: str,
    prior_order: tuple[int, ...] | None,
) -> tuple[int, tuple[int, ...], Mapping[str, Any], Mapping[str, Any]]:
    if (
        transition.get("feature_cutoff_is_strict_prefix") is not True
        or transition.get("current_event_present_in_state_before") is not False
        or transition.get("future_outcomes_in_state_before") is not False
    ):
        raise policy_v2.ExternalHistoricalFuryPolicyV2Error(
            "TRANSITION_NOT_STRICT_PREFIX",
            "V3 requires the unchanged Stage5 strict-prefix transition",
        )
    trace_index = policy_v2._nonnegative_integer(
        transition.get("trace_index"), "trace_index"
    )
    order = tuple(
        policy_v2._nonnegative_integer(value, "order component")
        for value in policy_v2._array(transition.get("order_key"), "order_key")
    )
    if len(order) != 5 or (prior_order is not None and order <= prior_order):
        raise policy_v2.ExternalHistoricalFuryPolicyV2Error(
            "TRANSITION_ORDER_INVALID", "V3 transitions are not strictly ordered"
        )
    if trace_index >= len(trace):
        raise policy_v2.ExternalHistoricalFuryPolicyV2Error(
            "TRANSITION_TRACE_REFERENCE_INVALID", "V3 trace index is out of range"
        )
    source = policy_v2._mapping(trace[trace_index], "transition trace source")
    if (
        source.get("trace_kind") != "EXACT_PLAYER_EVENT"
        or source.get("player_guid") != focal_guid
        or source.get("order_key") != list(order)
    ):
        raise policy_v2.ExternalHistoricalFuryPolicyV2Error(
            "TRANSITION_TRACE_REFERENCE_MISMATCH",
            "V3 transition does not point to its exact actor trace row",
        )
    state = policy_v2._mapping(transition.get("state_before"), "state_before")
    if (
        state.get("prefix_trace_exclusive_index") != trace_index
        or state.get("prefix_trace_event_count") != trace_index
        or state.get("cutoff_exclusive_order_key") != list(order)
    ):
        raise policy_v2.ExternalHistoricalFuryPolicyV2Error(
            "TRANSITION_PREFIX_INDEX_MISMATCH",
            "V3 state does not end exactly before the current trace row",
        )
    label = policy_v2._mapping(
        transition.get("current_event_label"), "current_event_label"
    )
    return trace_index, order, state, label


def process_player_transitions(
    *,
    player: Mapping[str, Any],
    trace: Sequence[Mapping[str, Any]],
    instance_ref: str,
    encounter_id: str,
    inventory_index: CharacterInventoryIndex | None = None,
) -> PlayerDiagnostic:
    """Build V3 labels/contexts for one player without reading future rows."""

    metadata = policy_v2._mapping(player.get("player"), "player metadata")
    focal_guid = policy_v2._text(metadata.get("guid"), "player guid")
    result = PlayerDiagnostic()
    history: list[PrefixAction] = []
    pending_starts: dict[tuple[str, str], int] = {}
    prior_order: tuple[int, ...] | None = None
    transitions = policy_v2._array(
        player.get("prefix_transitions"), "prefix_transitions"
    )
    for raw_transition in transitions:
        transition = policy_v2._mapping(raw_transition, "prefix transition")
        trace_index, order, state, label = _validate_transition(
            transition,
            trace=trace,
            focal_guid=focal_guid,
            prior_order=prior_order,
        )
        prior_order = order
        result.audit["transitions_inspected"] += 1
        event_type = policy_v2._text(label.get("event_type"), "event_type")
        spell = policy_v2._mapping(label.get("spell"), "spell")
        classification = classify_action_event(event_type=event_type, spell=spell)

        if (
            label.get("attribution_kind") != "DIRECT_FRIENDLY_PLAYER"
            or label.get("source_lane") != "FRIENDLY_PLAYER"
        ):
            result.audit[f"classified:{classification.role}"] += 1
            result.audit["non_direct_player_event_excluded"] += 1
            continue

        timestamp_ms = order[1]
        pending_starts = {
            key: start
            for key, start in pending_starts.items()
            if 0 <= timestamp_ms - start <= policy_v2.START_GO_PAIR_MAX_MS
        }
        identity = (
            _action_identity(classification.action_key, label)
            if classification.action_key is not None
            else None
        )
        if event_type == "FAIL":
            result.audit[f"classified:{classification.role}"] += 1
            if identity is not None:
                pending_starts.pop(identity, None)
            result.audit["failed_attempts_excluded"] += 1
            continue
        if event_type == "GO" and identity is not None and identity in pending_starts:
            pending_starts.pop(identity)
            result.audit[f"classified:{ROLE_PAIRED_RESULT}"] += 1
            result.audit["paired_go_deduplicated"] += 1
            continue
        result.audit[f"classified:{classification.role}"] += 1
        if classification.role not in {
            ROLE_CONTROLLABLE_START,
            ROLE_CONTROLLABLE_INSTANT_GO,
        }:
            result.audit["nondecision_events_excluded"] += 1
            continue

        assert classification.action_key is not None
        assert classification.lane is not None
        if event_type == "START":
            assert identity is not None
            pending_starts[identity] = timestamp_ms

        event_index = order[2]
        inventory: CharacterInventorySnapshot | None = None
        join_outcome = "inventory_index_unavailable"
        if inventory_index is not None:
            inventory, join_outcome = inventory_index.select(
                instance_ref=instance_ref,
                encounter_id=encounter_id,
                player_guid=focal_guid,
                event_index=event_index,
            )
        contexts = _contexts_with_observable_state(
            state=state,
            trace=trace,
            focal_guid=focal_guid,
            current_timestamp_ms=timestamp_ms,
            history=history,
            inventory=inventory,
        )
        target_role, usable = policy_v2._target_role(
            label=label, state=state, focal_guid=focal_guid
        )
        action_key = policy_v2._canonical_bytes(
            {
                "action_key": classification.action_key,
                "target_role": target_role,
            }
        ).decode("utf-8")
        result.decisions.append(
            AcceptedDecision(
                action_key=classification.action_key,
                event_role=classification.role,
                trace_index=trace_index,
                voting_usable=usable,
                inventory_join_outcome=join_outcome,
                contexts=contexts,
            )
        )
        history.append(
            PrefixAction(
                action_key=classification.action_key,
                lane=classification.lane,
                timestamp_ms=timestamp_ms,
                trace_index=trace_index,
            )
        )
        result.audit["controllable_decisions_retained"] += 1
        if not usable:
            result.audit["unsupported_nonvoting_targets_excluded"] += 1
            continue
        result.aggregate.add(contexts, action_key)
        result.audit["accepted_voting_labels"] += 1
        result.feature_coverage["accepted_voting_labels"] += 1
        result.feature_coverage[f"inventory_join:{join_outcome}"] += 1
        if inventory is not None:
            result.feature_coverage["inventory_matched"] += 1
            if inventory.gear_slots:
                result.feature_coverage["gear_observed"] += 1
            if inventory.talent_trees is not None:
                result.feature_coverage["talents_observed"] += 1
        if len(history) > 1:
            result.feature_coverage["prior_controllable_action_observed"] += 1
        if any(row.lane == "gcd" for row in history[:-1]):
            result.feature_coverage["prior_gcd_action_observed"] += 1
        if any(row.lane == "queue" for row in history[:-1]):
            result.feature_coverage["prior_queue_decision_observed"] += 1
    return result


def evaluate_outer_components(
    components: Mapping[str, policy_v2._Aggregate],
    *,
    fold_count: int = policy_v2.DEFAULT_FOLD_COUNT,
    split_seed: int = policy_v2.DEFAULT_SPLIT_SEED,
) -> JSONMap:
    """Use V2's unchanged connected-component evaluator, never a row split."""

    return policy_v2._evaluate_component_split(
        components,
        fold_count=fold_count,
        split_seed=split_seed,
        alpha=policy_v2.DEFAULT_SMOOTHING_ALPHA,
        backoff_strength=policy_v2.DEFAULT_BACKOFF_STRENGTH,
    )


def analyze_wave_records(
    waves: Iterable[Mapping[str, Any]],
    *,
    node_to_outer_component: Mapping[str, str],
    inventory_by_instance: Mapping[str, CharacterInventoryIndex] | None = None,
) -> JSONMap:
    """Run a bounded in-memory V3 diagnostic over already-selected waves."""

    by_outer: dict[str, policy_v2._Aggregate] = defaultdict(policy_v2._Aggregate)
    audit: Counter[str] = Counter()
    feature_coverage: Counter[str] = Counter()
    for wave in waves:
        identity = policy_v2._mapping(wave.get("wave"), "wave identity")
        instance_ref = policy_v2._text(identity.get("instance_id"), "instance_id")
        encounter_id = policy_v2._text(identity.get("encounter_id"), "encounter_id")
        trace = [
            policy_v2._mapping(row, "trace row")
            for row in policy_v2._array(wave.get("exact_trace"), "exact_trace")
        ]
        for raw_player in policy_v2._array(wave.get("players"), "players"):
            player = policy_v2._mapping(raw_player, "wave player")
            metadata = policy_v2._mapping(player.get("player"), "player metadata")
            spec = policy_v2._mapping(player.get("warrior_spec_lane"), "warrior_spec_lane")
            eligibility = policy_v2._mapping(
                player.get("eligibility_observation"), "eligibility_observation"
            )
            if (
                str(metadata.get("class") or "").upper() != "WARRIOR"
                or spec.get("partition_key") != policy_v2.FURY_LANE
                or eligibility.get("historical_fury_candidate_filter_passed") is not True
            ):
                audit["nontraining_or_nonfury_episode_excluded"] += 1
                continue
            instance_node, player_node, component = policy_v2._episode_nodes_and_outer_component(
                player, node_to_outer_component
            )
            diagnostic = process_player_transitions(
                player=player,
                trace=trace,
                instance_ref=instance_ref,
                encounter_id=encounter_id,
                inventory_index=(inventory_by_instance or {}).get(instance_ref),
            )
            diagnostic.aggregate.observe_episode(
                player_node=player_node, instance_node=instance_node
            )
            by_outer[component].merge(diagnostic.aggregate)
            audit.update(diagnostic.audit)
            feature_coverage.update(diagnostic.feature_coverage)
    return {
        "schema": SCHEMA,
        "status": STATUS,
        "split_contract": {
            "unit": "upstream connected component of full-roster instance, guild, and player nodes",
            "row_random_split": False,
            "prefix_causality": "strictly before current exact EventMeta order_key",
        },
        "action_label_audit": dict(sorted(audit.items())),
        "feature_coverage": _coverage_report(feature_coverage),
        "outer_component_evaluation": evaluate_outer_components(by_outer),
        "missing_dynamic_state": list(MISSING_DYNAMIC_STATE),
    }


def _coverage_report(counts: Mapping[str, int]) -> JSONMap:
    denominator = int(counts.get("accepted_voting_labels", 0))
    return {
        "counts": dict(sorted((key, int(value)) for key, value in counts.items())),
        "rates_over_accepted_voting_labels": {
            key: value / denominator
            for key, value in sorted(counts.items())
            if key != "accepted_voting_labels" and denominator
        },
    }


def admission_inventory_coverage(manifest: Mapping[str, Any]) -> JSONMap:
    entries = manifest.get("instances")
    if not isinstance(entries, list):
        raise ValueError("admission manifest instances must be an array")
    totals: Counter[str] = Counter()
    statuses: Counter[str] = Counter()
    for entry in entries:
        if not isinstance(entry, Mapping):
            raise ValueError("admission instance must be an object")
        evidence = entry.get("combatant_info_evidence")
        if not isinstance(evidence, Mapping):
            raise ValueError("admission instance lacks CombatantInfo evidence")
        statuses[str(evidence.get("status"))] += 1
        for key in (
            "message_count",
            "message_with_gear_count",
            "message_with_talents_count",
            "unanchored_message_count",
            "identity_conflict_count",
            "unique_player_guid_count",
        ):
            value = evidence.get(key)
            if isinstance(value, bool) or not isinstance(value, int):
                raise ValueError(f"CombatantInfo {key} must be an integer")
            totals[key] += value
        obj = evidence.get("object")
        if not isinstance(obj, Mapping) or isinstance(obj.get("size_bytes"), bool) or not isinstance(obj.get("size_bytes"), int):
            raise ValueError("CombatantInfo object size is missing")
        totals["object_bytes"] += obj["size_bytes"]
    messages = totals["message_count"]
    return {
        "instance_count": len(entries),
        "status_counts": dict(sorted(statuses.items())),
        **dict(sorted(totals.items())),
        "gear_message_coverage": totals["message_with_gear_count"] / messages if messages else None,
        "talent_message_coverage": totals["message_with_talents_count"] / messages if messages else None,
    }


def quantitative_hpc_assessment(inventory_coverage: Mapping[str, Any]) -> JSONMap:
    total_labels = 867_659
    whitelist_labels = 182_911
    unpaired_go = 604_900
    known_proc_rows = 12_970 + 12_721
    gear_coverage = inventory_coverage.get("gear_message_coverage")
    talent_coverage = inventory_coverage.get("talent_message_coverage")
    verified_instances = int(
        policy_v2._mapping(
            inventory_coverage.get("status_counts"), "status_counts"
        ).get("VERIFIED_LOCAL_OFFICIAL_STREAM", 0)
    )
    static_ready = (
        inventory_coverage.get("instance_count") == 84
        and verified_instances == 84
        and isinstance(gear_coverage, (int, float))
        and gear_coverage == 1.0
        and isinstance(talent_coverage, (int, float))
        and talent_coverage >= 0.99
    )
    return {
        "frozen_v2_reduction": {
            "all_labels": total_labels,
            "unpaired_go_labels": unpaired_go,
            "unpaired_go_share": unpaired_go / total_labels,
            "known_flurry_plus_deep_wounds_rows": known_proc_rows,
            "known_proc_share_of_all_labels": known_proc_rows / total_labels,
            "known_proc_share_of_unpaired_go": known_proc_rows / unpaired_go,
            "fifteen_action_whitelist_labels": whitelist_labels,
            "whitelist_retention": whitelist_labels / total_labels,
            "whitelist_excluded": total_labels - whitelist_labels,
            "outer_top1": 0.31894,
            "outer_top3": 0.57758,
            "top1_gap_to_v2_gate": 0.31894 - 0.45,
            "top3_gap_to_v2_gate": 0.57758 - 0.80,
        },
        "inventory_coverage": dict(inventory_coverage),
        "next_hpc_judgment": (
            "WORTH_ONE_BOUNDED_84_INSTANCE_DIAGNOSTIC"
            if static_ready
            else "BLOCKED_ON_STATIC_INVENTORY_COVERAGE"
        ),
        "scientific_scope": (
            "compare V3 ontology plus causal static/timing features against the frozen "
            "15-action result; this does not authorize adoption or broad hyperparameter search"
        ),
        "required_before_adoption": (
            "V3 must improve held-out component top1 and top3 together without worsening "
            "contextual log loss or calibration; current dynamic-state gaps remain explicit"
        ),
        "missing_dynamic_state": list(MISSING_DYNAMIC_STATE),
    }


def _load_json(path: Path) -> Mapping[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, Mapping):
        raise ValueError(f"JSON root must be an object: {path}")
    return value


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Report V3 label/state gaps without scanning Stage5 partitions"
    )
    parser.add_argument(
        "--admission-manifest",
        type=Path,
        default=DEFAULT_ADMISSION_MANIFEST,
    )
    args = parser.parse_args(argv)
    coverage = admission_inventory_coverage(_load_json(args.admission_manifest))
    print(json.dumps(quantitative_hpc_assessment(coverage), ensure_ascii=False, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
